services:
  - type: web
    name: whistlebot-whatsapp
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app --workers=2 --threads=4 --timeout=60
    envVars:
      - key: FLASK_ENV
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: ENABLE_EMAIL_NOTIF
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: COMPLIANCE_EMAIL
        sync: false
      - key: ALLOW_ADMIN_BASIC_AUTH
        sync: false
      - key: ADMIN_BASIC_AUTH_USER
        sync: false
      - key: ADMIN_BASIC_AUTH_PASS
        sync: false
